"""add is_done flag to supplyitem

Revision ID: 0211ad3236b1
Revises: 6f2bc5e1d5c7
Create Date: 2020-07-23 19:46:05.581423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0211ad3236b1'
down_revision = '6f2bc5e1d5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('is_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'is_done')
    # ### end Alembic commands ###
