"""location to stays

Revision ID: 24c71238e35b
Revises: 11ed609d2f90
Create Date: 2020-07-24 23:48:26.095186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24c71238e35b'
down_revision = '11ed609d2f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stays', sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stays', 'location')
    # ### end Alembic commands ###
