"""remove user_id from stays

Revision ID: 58921ced717d
Revises: 34e69bf44bdc
Create Date: 2020-08-14 20:42:14.532768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58921ced717d'
down_revision = '34e69bf44bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stays_user_id_fkey', 'stays', type_='foreignkey')
    op.drop_column('stays', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stays', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('stays_user_id_fkey', 'stays', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
