"""add creaeated_at column

Revision ID: 62e72ba80f41
Revises: 8bef32734c8a
Create Date: 2020-07-12 21:55:31.574268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e72ba80f41'
down_revision = '8bef32734c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('flights', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('stays', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('trips', 'created_at')
    op.drop_column('stays', 'created_at')
    op.drop_column('flights', 'created_at')
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###
