"""remove user_id from flights

Revision ID: 9e25e8b67c93
Revises: ec7aeffc16dd
Create Date: 2020-08-13 22:27:25.091874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e25e8b67c93'
down_revision = 'ec7aeffc16dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flights_user_id_fkey', 'flights', type_='foreignkey')
    op.drop_column('flights', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('flights_user_id_fkey', 'flights', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
