"""notes and estimate cost

Revision ID: e72b07553fd2
Revises: 24c71238e35b
Create Date: 2020-08-10 22:06:10.170240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72b07553fd2'
down_revision = '24c71238e35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('cost_estimate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('supplies', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'notes')
    op.drop_column('supplies', 'cost_estimate')
    # ### end Alembic commands ###
