"""add date to stay and datetime to flights

Revision ID: f9795b50a253
Revises: 62e72ba80f41
Create Date: 2020-07-15 19:51:14.332521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9795b50a253'
down_revision = '62e72ba80f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('end_datetime', sa.DateTime(), nullable=True))
    op.add_column('flights', sa.Column('start_datetime', sa.DateTime(), nullable=True))
    op.add_column('stays', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('stays', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stays', 'start_date')
    op.drop_column('stays', 'end_date')
    op.drop_column('flights', 'start_datetime')
    op.drop_column('flights', 'end_datetime')
    # ### end Alembic commands ###
